# Generated by Django 2.2.19 on 2021-04-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='aaa',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
